### ISSUE TITLE
JavaScript refactoring and CI

### ISSUE THREAD

**Issue by redaxmedia** [redaxscript/redaxscript#185]
## Refactor / Plan

- [x] Rip of all Javascript and start from scratch (TDD)
- [x] There is no `base` JavaScript anymore - move all to `/templates`  `/modules` directory
- [x] Split `rs.plugin` to `rs.templates` and `rs.modules`
- [ ] Each ES6 module has to be in it's own file / namespace similar to PHP
- [ ] Get rid of hard codes CSS classes inside JavaScript
- [x] Remove `Plugins` from documentation
- [x] Remove `Basics - Shortcuts` from documentation

## Linter / Grunt

- [x] Migrate from JSCS to ESLint using a good preset
- [x] Use load-grunt-tasks in gruntfile.js

## Unit testing / CI

- [x] Remove the Qunit Module
- [ ] Use Mocha, Chai and Blanket or maybe Jest
- [ ] Install and run the module inside Travis CI
- [ ] Use Karma and Browserstack

## Pure CSS / Reduce JS

- [ ] Accordion: http://www.hongkiat.com/blog/css-only-accordion/
- [ ] Tab: https://stanhub.com/tutorials/responsive-horizontal-css-only-tabs
- [ ] Admin Panel
- [x] Admin Docks (description on hover)

## Third party

- [ ] Replace dialog with Native or JavaScript Modal solution
- [x] Alias generator should be replaced with: https://github.com/pid/speakingurl
- [ ] Switch to a auto-installed form validation module: https://github.com/hyperform/hyperform
- [x] Replace jQuery Plugings with Vanilla Plugins

## Bugs

- [ ] JavaScript powered password validation on installation wizard not working

**Comment by redaxmedia** [comment]
Done
