### ISSUE TITLE
Release stages for 4.0.0

### ISSUE THREAD

**Issue by redaxmedia** [redaxscript/redaxscript#586]
Beta 1
=====

General
----------

- [x] **PERFORMANCE:** Use full qualified functions for PHP internals
- [x] **TASK:** Release updated website
- [x] **TASK:** Update files in download sync job

Console
----------

- [x] **BUG:** Grunt CLI issue with `grunt.option.flags()`
- [x] **BUG:** Uninstall command in Console gives error but actually works
- [x] **FEATURE:** Implement `halt-on-error` in Console to break a CI build

Module
---------

- [x] **BUG:** PageCache module caches unminified assets

Beta 2
=====

General
----------

- [x] **FEATURE:** Improve code with additional interfaces
- [x] **FEATURE:** Use latest postcss-custom-properties plugin

Navigation
-------------

- [x] **BUG:** Class `rs-item-active` is not added to active item 
- [x] **FEATURE:** Show "no content is present" for empty navigation

Module
---------

- [x] **WONTFIX:** ~~Table Sorter's handle not vertical align in Microsoft Edge~~
- [x] **PERFORMANCE:** Remove PHP side compression from PageCache module
- [x] **FEATURE:** Introduce a dialog module to confirm on deletion / unsafed data
- [x] **FEATURE:** Remove Config class from all modules and introduce `$_optionArray`

Search
---------

- [x] **FEATURE:** Restore range limit `3 - 100` instead of adding pagination

Beta 3
=====

General
-----------

- [x] **FEATURE:** Use latest postcss-color-gray plugin
- [x] **FEATURE:** Remove `cursor: pointer` for active tab and accordion items
- [x] **BUG:**  Default titles like login, logout, admin etc. are missing in template helper
- [x] **BUG:** Fix docker container to work with latest release

QA
----

- [x] **TASK:** Split suite to unit and acceptance testing
- [x] **TASK:** Run acceptance testing on CI
- [x] **TASK:** Acceptance story: Installation
- [x] **TASK:** Acceptance story: Login

Admin
--------

- [x]  **FEATURE:** Split `Admin\View\Helper` into `getArticles()`, `getCategories()` etc
- [x] **FEATURE:** Edit comment - only show articles in select field that have comments enabled
- [x] **FEATURE:** Edit category - only show categories in select field that have no parent itself

Profile
--------

- [x] **BUG:** Instantly take over changes (name, language etc.) to the Auth and Registry on save

Beta 4
=====

General
-----------

- [x] **BUG:** Homepage is being showed everywhere instead of root only
- [x] **BUG:** Fields on installation need to be reseted while switching the type
- [x] **BUG:** Page cache sometimes includes uncached assets (maybe invalid at same time)
- [x] **BUG:** Navigation in Header is broken when no article or category is present
- [x] **BUG:** Parent category in sidebar is hidden while browsing as of `... li:not(.rs-item-active) ...`
- [x] **FEATURE:** Add brotli compression

QA
----

- [x] **TASK:** Update to PHPUnit 8
- [x] **TASK:** Add void return types

Admin
--------

- [x] **FEATURE:** Line through corrupted modules with `status = 2` flag when viewing admin table
- [x] **BUG:** All contents were deleted - blank page instead of expected content not found
- [x] **BUG:** Prevent fatal error on corrupt modules without a folder and show something went wrong

Bootstrap
------------

- [x] **PERFORMANCE:**: Prevent redundant queries to settings table
- [x] **PERFORMANCE:**: Prevent useless queries containing `WHERE `alias` = ''`
- [x] **PERFORMANCE:**: Equal categories and articles limit in header and sidebar
- [x] **PERFORMANCE:**: Improve `Bootstrap\Content` as it fires 3 queries every time
- [x] **PERFORMANCE:**: Stop content lookup on default pages such as login or logout

Beta 5
=====

General
----------
- [x] **FEATURE**: Move `_animate.css` to external project / repository
- [x] **FEATURE**: Remove `float: left` from notes and therefore get rid of clearfix helpers
- [x] **FEATURE:** Sibling support for `View\Extra` and `View\Article` - should be a edge case fallback and not part of default queries as the performance would be very bad
- [x] **TASK**: Join "cagegories" and "articles" header menu to "menu" inside website's template

Admin
--------

- [x] **FEATURE:** Take over status changes and deletion from contents to its children
- [x] **WONTFIX:** ~~Reorder category's children when viewing the admin table~~ (dragula does not support multiple items at this moment)

QA
----

- [x] **TASK:** Implement more from [slevomat/coding-standard](https://github.com/slevomat/coding-standard)
- [x] **TASK:** Acceptance story: Content page
- [x] **TASK:** Acceptance story: Error page
- [x] **TASK:** Acceptance story: Console
- [x] **TASK:** Acceptance story: Search

Stable
=====

General
----------

- [x] **BUG:** Gallery does not work with cached pages
- [x] **TASK:** Add gallery to website and improve styling
- [x] **TASK:** Remove Beta badge from website
- [x] **TASK:** Fix ReflectionType::__toString() as of deprecation since PHP 7.4
- [x] **TASK:** Refactor view related `init()` to `return this`
- [x] **TASK:** Refactor all Singleton classes to `get() : string` and `getArray() : array`

QA
----

- [x] **TASK:** Unit testing for admin controllers and models
- [x] **TASK:** Allow testing suite to run in random order to support Infection greater than 0.10.6

Documentation
-------------------

- [x] **TASK:** Add markdown tables for the options in Template Tags
- [x] **TASK:** Add windows setup using PowerShell scripting
- [x] **TASK:** Refresh and extend the Reference guide

**Comment by RoyalC** [comment]
blank page wwhen i want to test it with uwamp server php 7.03 mysql 5.7. I download the latest bild on  site and git , uncompress the whole archive in my folder and try it , by http://127.0.0.1, and nothing ,blank page, event if put /install.php, blank page.

Any Idea ?

**Comment by redaxmedia** [comment]
Hello,

thank you for testing the beta.

Short anwser: You need to download UwAmp bundled with PHP 7.2 mention at the [requirements](https://redaxscript.com/documentation/basics/requirements-1002) page

Long anwser / You don't need a prebuild server package:

1. Use the [redaxscript-powershell](https://github.com/redaxscript/redaxscript-powershell) - a collection of setup routines for Windows
1. Check out the [quick start](https://redaxscript.com/documentation/basics/quick-start-1001) that allows you to serve Redaxscript with the internal PHP server
1. You need that kind of setup anyway for proper development of templates

**Comment by RoyalC** [comment]
with 7.2 it work like a charm 👍

**Comment by redaxmedia** [comment]
Great! Still need help? You can chat with me on <a class="rs-link-default" href="https://m.me/redaxscript">Facebook</a> for live support.

Consider to give Redaxscript a star on GitHub... 👍
