### ISSUE TITLE
Admin - Views and helper

### ISSUE THREAD

**Issue by redaxmedia** [redaxscript/redaxscript#68]
This issue affects <code>includes/admin_admin.php</code>:

- [x] Admin/Panel
- [x] Admin/Dock
- [x] Admin/Control

and <code>includes/admin_list.php</code>:

- [x] Admin/View/CategoryTable
- [x] Admin/View/ArticleTable
- [x] Admin/View/ExtraTable
- [x] Admin/View/CommentTable
- [x] Admin/View/ModuleTable
- [x] Admin/View/UserTable
- [x] Admin/View/GroupTable

**Comment by redaxmedia** [comment]
Done
